# Generated by Django 6.0.3 on 2026-03-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0003_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_student_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('head_attention_score', models.FloatField(default=0.0)),
                ('posture_score', models.FloatField(default=0.0)),
                ('hand_activity_score', models.FloatField(default=0.0)),
                ('writing_score', models.FloatField(default=0.0)),
                ('motion_score', models.FloatField(default=0.0)),
                ('total_engagement_score', models.FloatField(default=0.0)),
                ('activity_label', models.CharField(choices=[('active', 'Active'), ('moderate', 'Moderate'), ('passive', 'Passive')], default='passive', max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='lessons.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.student')),
            ],
            options={
                'db_table': 'activity_logs',
                'indexes': [models.Index(fields=['lesson', 'timestamp'], name='activity_lo_lesson__274e9e_idx'), models.Index(fields=['lesson', 'temp_student_id'], name='activity_lo_lesson__49457e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_student_id', models.CharField(max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='lessons.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.student')),
            ],
            options={
                'db_table': 'student_sessions',
                'unique_together': {('lesson', 'temp_student_id')},
            },
        ),
    ]
