# Generated by Django 6.0.3 on 2026-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='behavior_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='material_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
