# Generated by Django 6.0.3 on 2026-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_activitylog_behavior_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='face_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='face_crops/'),
        ),
    ]
