# Generated by Django 5.x on 2026-04-05

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='camera_source',
            field=models.CharField(blank=True, help_text='RTSP URL, webcam index, or stream URL', max_length=500, null=True),
        ),
    ]
