# Generated by Django 6.0.3 on 2026-03-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_engagement', models.FloatField(default=0.0)),
                ('active_count', models.IntegerField(default=0)),
                ('passive_count', models.IntegerField(default=0)),
                ('moderate_count', models.IntegerField(default=0)),
                ('peak_engagement_time', models.DateTimeField(blank=True, null=True)),
                ('low_engagement_time', models.DateTimeField(blank=True, null=True)),
                ('total_students_detected', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='lessons.lesson')),
            ],
            options={
                'db_table': 'lesson_reports',
            },
        ),
    ]
